version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: golang:1.13.3-alpine
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Call to rancher to deploy"
          command: |
              docker run --rm -it \
                -e CATTLE_ACCESS_KEY="$CATTLE_ACCESS_KEY" \
                -e CATTLE_SECRET_KEY="$CATTLE_SECRET_KEY" \
                -e CATTLE_URL="$CATTLE_URL" \
                etlweather/gaucho upgrade $RANCHER_EXAMPLE_GO \
                --imageUuid 'docker:krieng/training:latest' \
                --batch_size 3 --start_first \
                --auto_complete --timeout 600 \
                /
      - run: echo Done
